---
title: " "
pagetitle: "Honors & Awards"
---
<p>&nbsp;</p>

### Honors & Awards
-  2025  James Dincolo Outstanding Research Award
-  2024  Prochaska Outstanding Teaching Award  
-  2023  *Poets&Quants* Best 40-Under-40 MBA Professor Worldwide  
-  2023  Distinguished Winner, AMA-EBSCO-RRBM Award for Responsible Research in Marketing
-  2023  Fellow, 2023 ISMS Early-Career Scholars Camp
-  2022  Kemper Professor Award Grant
-  2022	 Inaugural Winner, Financial Times Responsible Business Education Award
-  2022	 Finalist, Paul E. Green Best Paper Award

-  2022	 University of New Mexico Inspirational Young Alumnus Award 
-  2022	 Finalist, AMA-EBSCO-RRBM Award for Responsible Research in Marketing
-  2022	 Faculty Mentor, Marketing Strategy Doctoral Consortium, Texas A&M University
-  2021	 Grow the Good in Business Faculty Research Award, Mendoza College of Business
-  2021	 Finalist, AMA/Marketing Science Institute/H. Paul Root Best Paper Award 

-  2021	 Winner, John A. Howard AMA Doctoral Dissertation Award
-  2021	 Winner, Texas A&M Distinguished Dissertation Award
-  2019	 Finalist, AMA/Marketing Science Institute/H. Paul Root Best Paper Award
-  2019	 Fellow, AMA-Sheth Foundation Doctoral Consortium, New York University 
-  2019	 Dean’s Award for Outstanding Teaching, Texas A&M University 
-  2019	 Fellow, University of Houston Marketing Doctoral Symposium
-  2018	 Fellow, Academy of Marketing Science Doctoral Consortium
-  2016	 Fellow, ISBM PhD Camp on Research in B2B Markets, Emory University
-  2015–2020	 PhD Enhancement Fellowship, Texas A&M University
-  2015–2020	 Department of Marketing Fellowship, Texas A&M University
-  2014,2015	 Albert & Mary Jane Black Endowed Fellowship, UNM Anderson Foundation
-  2013	 International Amigo Scholarship, University of New Mexico                                               
-  2011  Guanghua Best All-Round Student Award, Southwestern University of Finance and Economics                     
-  2010,2011	 Academic Excellence Scholarship, Southwestern University of Finance and Economics





