---
title: " "
pagetitle: "Research"
---
<p>&nbsp;</p>

### Publications
1. Chen, Yixing, Shrihari Sridhar, Kyuhong Han, Sonam Singh, Vikas Mittal, and Taehoon Im, “The Value of Safety Training for Business-to-Business Firms,” ***Journal of Marketing Research***, forthcoming. [Link](https://journals.sagepub.com/doi/10.1177/00222437231222857)
   - Previously circulated under the title "Return on Safety Training"

&nbsp;

2.  Chen, Yixing, Vikas Mittal, and Shrihari Sridhar (2021), “Investigating the Academic Performance and Disciplinary Consequences of School District Internet Access Spending,” ***Journal of Marketing Research***, 58 (1), 141-162. [Link](https://journals.sagepub.com/doi/pdf/10.1177/0022243720964130); [Appendix](https://journals.sagepub.com/doi/suppl/10.1177/0022243720964130/suppl_file/Web_Appendix_FINAL_(Chen_Mittal_Sridhar).pdf)
    - **Distinguished Winner, 2023 AMA-EBSCO-RRBM Award for Responsible Research in Marketing**
    - **Finalist, 2021 Paul E. Green Award (JMR Best Paper Award)** 
    - [Top 1%](https://sage.altmetric.com/details/94875362#score) of the Attention Scores of all research outputs tracked by Altmetric
    - Previously circulated under the title "Broadband Internet Access: A Double-Edged Sword for K-12 Education"
    - Media Coverage: [Notre Dame News](https://news.nd.edu/news/internet-access-spending-in-public-school-districts-increases-test-scores-but-also-disciplinary-problems-study-shows/), [K-12 Dive](https://www.k12dive.com/news/study-increased-internet-access-improves-achievement-district-finances/595246/), [Science Daily](https://www.sciencedaily.com/releases/2021/02/210216133432.htm), [Newswise](https://www.newswise.com/articles/internet-access-spending-in-public-school-districts-increases-test-scores-but-also-disciplinary-problems-study-shows), [sciencenewsnet.in](https://sciencenewsnet.in/internet-access-spending-in-public-school-districts-increases-test-scores-but-also-disciplinary-problems-study-shows/), [EurekAlert!](https://www.eurekalert.org/pub_releases/2021-02/uond-ias021621.php), [Phys.org](https://phys.org/news/2021-02-internet-access-schools-scores-disciplinary.html), [research@TexasA&M](https://research.tamu.edu/2021/04/27/schools-are-reaping-big-dividends-from-investments-in-online-access/)

&nbsp;

3.  Chen, Yixing, Ju-Yeon Lee, Shrihari Sridhar, Vikas Mittal, Katharine McCallister, and Amit G. Singal (2020), “Improving Cancer Outreach Effectiveness through Targeting and Economic Assessments: Insights from a Randomized Field Experiment,” ***Journal of Marketing***, 84 (3), 1–27 (Lead Article). [Link](https://journals.sagepub.com/doi/pdf/10.1177/0022242920913025); [Appendix](https://journals.sagepub.com/doi/suppl/10.1177/0022242920913025)
    - **Inaugural Winner, Financial Times Responsible Business Education Award on Academic Research** 
    - **Finalist, 2022 AMA-EBSCO-RRBM Award for Responsible Research in Marketing**
    - **Finalist, 2020 AMA/Marketing Science Institute/H. Paul Root Award (JM Best Paper Award)**
    - Invited for [JM Webinar Series: Insights for Managers](https://www.ama.org/jm-webinar-personalized-cancer-outreach-saves-both-lives-and-money/) and [Notre Dame 3-Minute Lightning Talk
](https://drive.google.com/file/d/11Apgq5RBHi4ZhKd8fP6kLEse4CShBmON/view)
    - [Top 2%](https://sage.altmetric.com/details/78200414#score) of the Attention Scores of all research outputs tracked by Altmetric
    - Media Coverage: [Financial Times](https://www.ft.com/content/d5ca2a09-333b-4f86-9e99-3a3bf1b86c75), [JM Scholarly Insights](https://www.ama.org/2020/03/18/applying-machine-learning-to-the-challenge-of-cancer-patient-outreach/), [Notre Dame News](https://research.nd.edu/news/combating-cancer-with-research-learn-how-notre-dame-researchers-are-changing-the-way-we-fight-cancer/), [Mendoza Business Magazine](https://bizmagazine.nd.edu/issues/2021/spring-2021/research-a-targeted-approach/), [Rice University News & Media](http://news.rice.edu/2020/03/31/machine-learning-can-help-increase-liver-cancer-screening-rates-says-rice-u-expert/), [Medical Xpress](https://medicalxpress.com/news/2020-03-personalization-machine-cancer-outreach-roi.html),  [EurekAlert!](https://www.eurekalert.org/pub_releases/2020-03/ama-hpa032420.php), [The Horizons Tracker
](http://adigaskell.org/2020/06/03/how-machine-learning-can-improve-patient-communication/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+adigaskell+%28Adi+Gaskell+says...%29), [Mirage News](https://www.miragenews.com/personalized-cancer-outreach-more-effective-study-finds/), [sciencenewsnet.in](https://sciencenewsnet.in/personalized-cancer-outreach-more-effective/), [Iowa State News](https://www.news.iastate.edu/news/2020/10/15/canceroutreach), [Rice Business Wisdom](https://business.rice.edu/wisdom/peer-reviewed-research-How-Personalized-Marketing-Can-Prevent-Cancer)

&nbsp;
    
4.  Kanuri, Vamsi K., Yixing Chen, and Shrihari Sridhar (2018), “Scheduling Content on Social Media: Theory, Evidence, and Application,” ***Journal of Marketing***, 82 (6), 89–108. [Link](https://journals.sagepub.com/doi/10.1177/0022242918805411); [Appendix](https://journals.sagepub.com/doi/suppl/10.1177/0022242918805411) 
    - **Finalist, 2018 AMA/Marketing Science Institute/H. Paul Root Award (JM Best Paper Award)**
    - Selected for publication in ***Harvard Business Review*** (digital article), [“A Study Shows the Best Times of Day to Post to Social Media”](https://hbr.org/2018/09/a-study-shows-the-best-times-of-day-to-post-to-social-media)
    - Media Coverage: [JM Scholarly Insights](https://www.ama.org/resources/Pages/social-media-strategists-here-is-the-science-behind-scheduling-content.aspx), @[Mays Headlines](https://mays.tamu.edu/wp-content/uploads/2019/01/@Mays-fall-2018-The-Business-of-Healthcare.pdf), [AACSB](https://bized.aacsb.edu/articles/2019/january/the-science-of-social-media), [Notre Dame News](https://news.nd.edu/news/capitalizing-on-sleep-wake-cycle-can-drastically-increase-digital-ad-profits-from-social-media-study-shows/), [Mendoza Business Magazine](http://bizmagazine.nd.edu/issues/2019/spring-2019/research-why-the-early-bird-gets-the-clicks/),  [ScienceDaily](https://www.sciencedaily.com/releases/2018/09/180918131711.htm), [Keller Center Report](https://www.baylor.edu/business/kellercenter/news.php?action=story&story=215313), [Phys.org](https://phys.org/news/2018-09-capitalizing-sleep-wake-drastically-digital-ad.html), [Communications of the Association for Computing Machinery](https://cacm.acm.org/news/231317-capitalizing-on-sleep-wake-cycle-can-drastically-increase-digital-ad-profits-from-social-media-study-shows/fulltext)                                 
&nbsp;

### Working Papers

1. Lei, Xiaoxia, Yixing Chen, and Ananya Sen (2023), “The Value of External Data for Digital Platforms: Evidence from a Field Experiment on Search Suggestions,” revise and resubmit at ***Management Science***. [Link](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4452804)
    - Selected for presentation at the [NBER Workshop of Digital Economics](https://www.nber.org/conferences/economics-digitization-spring-2023) 
    - Selected for presentation at the [NBER Economics of Artificial Intelligence Conference](https://www.nber.org/conferences/economics-artificial-intelligence-conference-fall-2023)

&nbsp;

2. Chen, Yixing\*, John P. Lalor\*, Wenchang Li, and Xin Luo (2023), "Advancing the Design of Online Review Systems in Education: A Field Experiment on Multidimensional Ratings," revise and resubmit at ***MIS Quarterly***. 

3. Hou, Liwen\*, Xinxue Qu\*, Yixing Chen, Kai Yu, and Ling Xue (2023), “Strategizing Value-Added Services for Platform Firms,” revise and resubmit at ***Production and Operations Management***.

4. Tong, Siliang\*, Shuang Zheng\*, Yixing Chen, Shrihari Sridhar, and Xianneng Li (2024), “Choice Architecture for a Better On-Demand Economy: A Field Experiment on Rating Disclosure in Mobile Search” working paper.

5. Zheng, Shuang, John P. Lalor, Yixing Chen, and Xianneng Li (2024), “Mitigating the Matthew Effect in Recommender Systems: Descriptive Evidence, Methodology, and Application” working paper.

6. Li, Wenchang, Yixing Chen, and John P. Lalor (2023), “Stars Are All You Need: A Distantly Supervised Pyramid Network for Document-Level End-to-End Sentiment Analysis,” working paper. [arXiv](https://arxiv.org/abs/2305.01710)

7. Chen, Yixing, Taehoon Im, Muzeeb Shaik, Narendra Bosukonda, Sonam Singh, Markus Blut, Vikas Mittal, Shrihari Sridhar, and Amit G. Singal (2021), “The Association of Patient Satisfaction and Quality of Care: Theory, Evidence, and Application,” resting paper. [Link](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3970182)
  
&nbsp;
\*Equal Contribution

&nbsp;

### Other Publications

1. Singal, Amit G., Yixing Chen, Shrihari Sridhar, Vikas Mittal, Hannah Fullington, Muzeeb Shaik, Akbar K. Waljee and  Jasmin Tiro (2022), “Novel Application of Predictive Modeling: Identifying Patients for a Tailored Approach to Promoting HCC Surveillance in Patients with Cirrhosis,” ***Clinical Gastroenterology and Hepatology***, 20 (8), 1795–1802. 2022 Impact Factor: 12.6. [Link](https://www.sciencedirect.com/science/article/pii/S1542356521002172)

2. Chen, Yixing, Shrihari Sridhar, and Vikas Mittal (2021), “Treatment Effect Heterogeneity in Randomized Field Experiments: A Methodological Comparison and Public Policy Implications,” ***Journal of Public Policy & Marketing***, 40 (4), 457–62 (Invited Article). [Link](https://doi.org/10.1177%2F07439156211032751) 
 
3. Chen, Yixing (2021), “Three Ways Nonprofits Grow Revenues,” ***Impact at JMR***. [Link](https://www.ama.org/2021/01/26/three-ways-nonprofits-grow-revenues/?utm_source=rss&utm_medium=rss&utm_campaign=three-ways-nonprofits-grow-revenues) 

4. Pickard, Matthew D., Catherine A. Roster, and Yixing Chen (2016), “Revealing Sensitive Information in Personal Interviews: Is Self-Disclosure Easier with Humans or Avatars and Under What Conditions,” ***Computers in Human Behavior***, 65, 23–30. [Link](https://www.researchgate.net/profile/Matthew-Pickard-2/publication/306421780_Revealing_sensitive_information_in_personal_interviews_Is_self-disclosure_easier_with_humans_or_avatars_and_under_what_conditions/links/5fa160eca6fdccfd7b97b0ae/Revealing-sensitive-information-in-personal-interviews-Is-self-disclosure-easier-with-humans-or-avatars-and-under-what-conditions.pdf)




