---
title: " "
pagetitle: "Talks"
---
<p>&nbsp;</p>

### Invited Presentations

- University of Texas at Austin (McCombs), October 2023 (scheduled)

- Southwestern University of Finance and Economics, July 2023

- East China University of Science and Technology (11th Operations and Supply Chain Workshop), July 2023

- Soochow University, June 2023 

- University of Notre Dame (First Lecture Series), August 2022

- Mays Business School, Texas A&M University (Marketing Strategy Doctoral Consortium), June 2022

- Wharton School, University of Pennsylvania (Responsible Research Summit), June 2022

- American University (NSF Convergence Workshop on Human-AI Frontier), May 2022

- Anderson School of Management, University of New Mexico, April 2022 

- Mays Business School, Texas A&M University (PhD seminar), February 2022 

- Renmin Business School, Renmin University of China, December 2021

- London School of Economics and Political Science, November 2021

- University of Notre Dame (First Lecture Series), August 2021

-	*Moment to See, Courage to Act* 3-Minute Lightning Talks, University of Notre Dame, April 2021

-	Southwestern University of Finance and Economics 95th Anniversary Seminar Series, October 2020

- New Ideas in Marketing Online Seminar Series, July 2020

- *Journal of Marketing* Webinar for Marketing Professionals, March 2020

- Mendoza College of Business, University of Notre Dame, August 2019

- School of International Business and Management, Sichuan International Studies University, June 2018 

&nbsp;
&nbsp;


### Selected Conference Presentations
- NBER Economics of Artificial Intelligence Conference, September 2023*

- Online seminar on the Economics of Platforms (Toulouse), July 2023*

- Columbia/Wharton Management, Analytics, and Data Conference, May 2023*

- NBER Workshop of Digital Economics, March 2023* 

- Workshop on Information Systems and Economics, Copenhagen Business School, December 2022*

- Marketing Dynamics Conference, Georgia State University, November 2022

- China India Insights Conference, USC Marshall School of Business, October 2022

- Conference on Information Systems and Technology, October 2022*

- AMA Summer Academic Conference (Paul E. Green Award Session and AMA EBSCO RRBM Awards Session), August 2022

- ISMS Marketing Science Conference, University of Chicago (virtual), June 2022*

- Neeley Analytics Conference, Texas Christian University, March 2022*

- *Journal of Marketing Research* Special Issue Conference on Mitigation in Marketing, September 2021 

- AMA Summer Academic Conference Special Session “Marketing in the Healthcare Sector”, August 2020*

- AMA Winter Educators’ Conference Special Session “Radically Innovative Research with Relevance for CRM”, February 2020*

- *Journal of Marketing Research* Special Issue Conference on Marketing and Education, February 2019

- AMA Winter Educators’ Conference, February 2018 

-	Thought Leader Conference on Marketing Strategy in Digital, Data-rich, and Developing market Environments, June 2017 


  *presentations by co-authors









