---
title: " "
pagetitle: "Teaching"
---

<p>&nbsp;</p>

### Mendoza College of Business, University of Notre Dame

- Marketing Analytics (MBA)
  - Spring 2021 (Rating: 5/5)
  - Spring 2022 (Rating: 4.7/5)
  - Spring 2023 (Rating: 4.9/5)
  - Recognition: [*Poets&Quants* Best 40-Under-40 MBA Professors Worldwide](https://poetsandquants.com/2023/06/05/2023-best-40-under-40-mba-professors-yixing-chen-mendoza-college-of-business-university-of-notre-dame/)

<p>&nbsp;</p>
- Marketing Analytics (Undergraduate)
  - Spring 2021 (Section 1 - Rating: 5/5; Section 2 - Rating: 5/5)
  - Spring 2022 (Section 1 - Rating: 5/5; Section 2 - Rating: 4.9/5)
  - Spring 2023 (Section 1 - Rating: 5/5; Section 2 - Rating: 4.7/5)

<p>&nbsp;</p>

#### Selected Student Comments

- “Fantastic class - one of the best professors in the MBA program I believe. Yixing took a topic that is complex and technical and really made it exciting and accessible to students. It was also helpful to have a guest speaker come in and share how this is used in real life. Overall, very pleased with the experience.”

- “Yixing is a master on the topic and he blends humor into his teaching style which makes it very easy to pay attention. He is able to explain very complex topics in easy ways. His slides are step by step and I loved it. He also does a great job identifying when the students are getting the material and if they are not he slows down. I also like how he brings the business judgment to the forefront of the analysis.”

- “His enthusiasm for the subject is unmatched, brings excitement to class everyday.  This class was easily the best that I have had this year, and it should be an essential course in the MSBA.”   

- “Professor Chen does such a good job at explaining concepts. His energy and excitement fuels the class and keeps everyone engaged. This was one of my favorite courses because the professor made it fun. Every class I walked away with more knowledge. He is a fantastic professor and I highly recommend everyone take a course of his. You will learn so much and enjoy the class lots. If you like marketing this professor will make you love it!” 

- “You can tell he is extremely passionate about this topic which helps engage the class. He takes you step by step through both the needed mathematical inputs and the theory and logic behind each step.” 

- “Extremely understanding of the varying comfort levels of students with statistics/analytics. Clear communication, leaves no room for confusion. Really excellent class material. Everything is backed by great examples that help with understanding. Approachable and kind!”

- “The step by step guide from data to business insights is the most useful knowledge I have learnt in Mendoza. Yixing's lecture is very engaging and rich.” 

- “Very clear in exposition of the material. Effective in building off of other student attempts at describing the material.”

- "It was truly a gift to be taught by someone who has such an undeniable depth of mastery in his course material. Yixing has made every effort not only to give us the information we need, but to explain its origin and application, and to help us practice communicating it effectively. He has clearly taken real-world challenges related to his subject area into consideration when designing the course. One such challenge is that of communicating statistical findings to a non-mathematically-oriented audience."

- "Yixing is hands down the best marketing/business professor I have ever had. He made me truly understand statistics for the first time and helped me see how marketing can be used to do good in the world."

<p>&nbsp;</p>

### Mays Business School, Texas A&M University


- Marketing Analytics (Undergraduate)
    - Fall 2018 (Section 1 - Rating: 4.89/5; Section 2 - Rating: 4.8/5)
    - Dean’s Award for Outstanding Teaching
<p>&nbsp;</p> 

#### Selected Student Comments

- “This course was the perfect balance of challenging and stimulating. I learned something new every class, and thoroughly enjoyed it.”

- “This course did an amazing job of preparing me for work post-grad as well as connecting to my other classes this semester.”

- “The course challenged me in my analytical thinking and the way I approach big data, I believe it is one of the most interesting classes I have taken here.”

- “The material in this class is perfectly picked. Everything works really well together to carefully explain all of the course material. Wonderful personality and cares so much about the students. Favorite professor of all time. So effective in teaching/engaging.”

- “By far one of the best professors I've ever had. The amount he poured into his students and teaching was immense.”

- “You always bring so much energy & fun to the class, it’s hard to not feel as passionate about the material as you. Favorite class of the semester!”

- “Yixing is an amazing professor and helped make a class that otherwise could have been very dull, very fun! He is super engaging and made coming to class fun. Overall, this was my favorite class this semester. Yixing made learning new/difficult material fun & interesting. I cannot speak highly enough of Yixing and this class.”
